name : Reusable gradel workflow
on :
  workflow_call:
     inputs:
       dockerimage:
           required: true
           type: string
           
jobs:
  my-job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/main.yml
        with:
          dockerimage: ${{ inputs.dockerimage }}
          
