name: Centralised Workflow

on:
workflow_call:
   inputs:
      dockerimage:
          required: true
          type: string
jobs:
   build:
     runs on: ubuntu-latest
   steps:
     -name: "calling"
      if : ${{inputs.dockerimage == "stellantis-harbor/openjdk11-mvn/v3.5.3/"
      uses:
     
  
