name: caller workflow
on: 
  push:
    branches: [main]

jobs:

  job1:
     uses: SamaRamya/Centralized-Workflow/.github/workflows/nodejs.yml@main
     with:
        dockerimage: def
        
  job2:
     uses: SamaRamya/Centralized-Workflow/.github/workflows/maven.yml@main
     with:
        dockerimage: ghi
       

