name: Centralised Workflow

on:
workflow_call:
   inputs:
      dockerimage:
          required: true
          type: string
jobs:
   build:
     runs on: ubuntu-latest
   steps:
     -name: "calling"
      if : ${{inputs.dockerimage == "stellantis-harbor/openjdk11-mvn/v3.5.3/"
      uses: https://github.com/SamaRamya/Centralized-Workflow/blob/main/.github/workflows/maven.yml@main
      if : ${{inputs.dockerimage == "stellantis-harbor/openjdk11-node12/v1.0/"
      uses:
      if : ${{inputs.dockerimage == "stellantis-harbor/java8-gradle7-node16/v1.0/"
      uses:
     
  
